name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCT_KEY }}
        export_default_credentials: true
    - name: Update Storage Bucket Contents
      run: gsutil -m rsync -r -c -d . gs://timothylin.me